//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eurovision.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public System.Guid Id { get; set; }
        public string SenderName { get; set; }
        public string P12 { get; set; }
        public string P10 { get; set; }
        public string P8 { get; set; }
        public string P7 { get; set; }
        public string P6 { get; set; }
        public string P5 { get; set; }
        public string P4 { get; set; }
        public string P3 { get; set; }
        public string P2 { get; set; }
        public string P1 { get; set; }
    }
}
